const browserGlobals = {
  AbortController: "readonly",
  Blob: "readonly",
  CSS: "readonly",
  CustomEvent: "readonly",
  DOMParser: "readonly",
  Element: "readonly",
  Event: "readonly",
  File: "readonly",
  FileReader: "readonly",
  FormData: "readonly",
  Headers: "readonly",
  HTMLButtonElement: "readonly",
  HTMLDetailsElement: "readonly",
  HTMLElement: "readonly",
  HTMLFormElement: "readonly",
  HTMLImageElement: "readonly",
  HTMLInputElement: "readonly",
  HTMLTextAreaElement: "readonly",
  HTMLVideoElement: "readonly",
  Image: "readonly",
  IntersectionObserver: "readonly",
  KeyboardEvent: "readonly",
  MouseEvent: "readonly",
  MutationObserver: "readonly",
  Notification: "readonly",
  Request: "readonly",
  ResizeObserver: "readonly",
  Response: "readonly",
  SVGElement: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  WebSocket: "readonly",
  Worker: "readonly",
  alert: "readonly",
  atob: "readonly",
  btoa: "readonly",
  confirm: "readonly",
  createImageBitmap: "readonly",
  crypto: "readonly",
  document: "readonly",
  fetch: "readonly",
  getComputedStyle: "readonly",
  history: "readonly",
  localStorage: "readonly",
  location: "readonly",
  matchMedia: "readonly",
  navigator: "readonly",
  performance: "readonly",
  queueMicrotask: "readonly",
  requestAnimationFrame: "readonly",
  sessionStorage: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  window: "readonly",
};

// Service-Worker- / Worker-Kontext-Globals (sw.js, pwa.js, media-worker).
// Als readonly global harmlos, da nie neu zugewiesen.
const workerGlobals = {
  self: "readonly",
  caches: "readonly",
  clients: "readonly",
  registration: "readonly",
  importScripts: "readonly",
  skipWaiting: "readonly",
  ServiceWorkerGlobalScope: "readonly",
  WorkerGlobalScope: "readonly",
  postMessage: "readonly",
};

const nodeGlobals = {
  Buffer: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  console: "readonly",
  global: "readonly",
  process: "readonly",
  require: "readonly",
  module: "readonly",
  exports: "writable",
  setImmediate: "readonly",
};

export default [
  {
    ignores: [
      "node_modules/**",
      "functions/node_modules/**",
      "apps/menyra-social/bundled/**",
      "dist/**",
      "tmp/**",
      "seed/export/**",
      "tests/mnyra-heart-runner/node_modules/**",
      "shared/vendor/**",
      "apps/menyra-social/vendor/**",
    ],
  },
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...browserGlobals,
        ...workerGlobals,
        ...nodeGlobals,
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: "warn",
    },
    rules: {
      "no-console": "off",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-undef": "error",
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    files: ["**/*.cjs"],
    languageOptions: {
      sourceType: "commonjs",
    },
  },
];
