// Editorial guidance for this reviewable template, not patient data.
export const AUDIT = [
  {id:"entry",title:"01 · Orientierung und Absender",question:"Bin ich richtig, und bekomme ich die versprochene Analyse?",mechanism:"Erwartungskontinuität: zuerst das Ergebnisversprechen der Werbung einlösen. Das Porträt macht den Absender greifbar; es ist kein Beweis für eine tatsächlich durchgeführte Untersuchung.",design:"Kompakter Markenbriefkopf, persönliche Anrede, zwei Orientierungssätze. Musterstatus separat, keine Fake-Verifizierung. Desktop-Navigation ist sekundär; auf dem Handy entfällt sie.",content:"Live: Name mit neutralem Fallback, geprüfter Autor, Datum und Beurteilungsstatus. Nur nach tatsächlicher Freigabe ‚Beurteilt von‘ anzeigen.",avoid:"Keine erfundenen Qualifikationen, Fallzahlen, Siegel oder persönlichen Arztzitate. Nicht zuerst das Set bewerben.",measure:"Versteht die Testperson nach dem Einstieg, was sie erhält und wer dafür verantwortlich ist?"},
  {id:"summary",title:"02 · Ergebnis und Einordnung",question:"Was ist bei mir wesentlich, und was bedeutet das?",mechanism:"Persönliche Relevanz und verständliche Handlungsperspektive. Das Hautbild wird eingeordnet, ohne normale Merkmale zum bedrohlichen Problem zu machen.",design:"Ein dunkler Ergebnisblock, darin Hauptbefund, albanischer Name, internationale Bezeichnung, verbaler Schweregrad und nächster Schritt. Kein zweiter dominanter Warnblock.",content:"Synthetisches Beispiel: leichte, überwiegend komedonale Akne. Produktbezug darf nur aus tatsächlich freigegebenen Befunden entstehen. Die internationale Bezeichnung ist kein Ersatz für eine Erklärung.",avoid:"Keine präzisen Messbalken ohne validierte Messbasis. Eine deskriptive Beobachtung niemals durch eine erfundene Diagnose ersetzen.",measure:"Kann die Person Hauptbefund und nächsten Schritt in eigenen Worten wiedergeben?"},
  {id:"findings",title:"03 · Priorisierte Beobachtungen",question:"Was wurde konkret gesehen?",mechanism:"Begründetes Vertrauen statt bloßer Autorität: wenige konkrete Beobachtungen stützen die Zusammenfassung und sind schneller zu erfassen als zehn gleichgewichtete Kennzahlen.",design:"Zwei kompakte Zeilen, kurze Lokalisierung, verständliche Kategorie. Maximal drei wesentliche Befunde im Hauptfluss; weitere Befunde in den Details.",content:"Morphologie und sichtbare Lokalisation priorisieren. Rötung nur unter Berücksichtigung der Aufnahmebedingungen. Keine Angaben zu unmessbarer Hydratation oder Hormonen.",avoid:"Nicht beurteilbar ist nicht gleich unauffällig. Keine erfundenen Anzahlen oder Prozentwerte zur Steigerung des wissenschaftlichen Eindrucks.",measure:"Erkennen Leser, welche Beobachtung die Empfehlung begründet?"},
  {id:"plan",title:"04 · Pflegeziel und Übergang",question:"Was möchte ich mit der Pflege erreichen?",mechanism:"Aus Information wird ein nachvollziehbarer Handlungsplan. Ein Ziel gibt Orientierung, ohne eine feststehende Zukunft zu behaupten.",design:"Eine kurze Zielbox vor den Produkten, keine dramatische Verschlechterungskurve. Der Weg zur Pflege wird über einen Sprunglink angeboten.",content:"Ziel beschreibt beobachtbare Veränderung und Verträglichkeit. 28 Tage sind ein Kontrollzeitraum, keine garantierte Heilungsfrist.",avoid:"Keine Angst vor Nichtkauf, künstliche Deadline oder Schuld durch die kostenlose Analyse.",measure:"Kann die Person Ziel, Beobachtungszeitraum und Grenzen voneinander unterscheiden?"},
  {id:"products",title:"05 · Produktrollen und Passung",question:"Warum gerade diese drei Produkte?",mechanism:"Konsistenz zwischen Befund und Empfehlung. Die Kundin soll selbst erkennen können, warum jeder Bestandteil enthalten ist.",design:"Gleiche Kartenstruktur, Reihenfolge der Anwendung, eine optisch maßvoll betonte aktive Pflege. Pro Karte Produkt, Menge, Rolle, eine persönliche Begründung; weitere Details aufklappbar.",content:"Zuordnung ausschließlich über stabile Produkt-IDs und fachlich geprüfte Indikationen. Reiniger ist kein Sonnenschutz. Akneprodukt nicht allein wegen sichtbarer Poren empfehlen.",avoid:"Keine zufällige Zuordnung anhand der Listenposition, keine unbelegten Wirkstoffkonzentrationen oder absoluten Verträglichkeitsversprechen. Keine generierten Packshots als reale Produktabbildung.",measure:"Frage: ‚Welches Produkt macht was, und warum gehört es in Ihr Set?‘"},
  {id:"routine",title:"06 · Anwendung überschaubar machen",question:"Wie passt das in meinen Alltag?",mechanism:"Wahrgenommene Umsetzbarkeit: eine verständliche Reihenfolge verringert organisatorische Unsicherheit. Keine erfundene Minutenangabe.",design:"Zwei ruhige Flächen für morgens und abends; auf dem Handy untereinander. Die Schritte werden in Textform genannt und bleiben ohne Icons verständlich.",content:"Exakte Mengen, Häufigkeiten und Wechselwirkungen aus dem freigegebenen Plan. Nicht enthaltene notwendige Ergänzungen ausdrücklich benennen.",avoid:"Das Design darf eine Routine nicht einfacher darstellen, als sie tatsächlich ist. Keine zusätzlichen aktiven Produkte ohne Abgleich.",measure:"Kann die Person den Ablauf erklären und erkennt sie, was nicht im Paket ist?"},
  {id:"offer",title:"07 · Paket und Entscheidung",question:"Was bekomme ich, was kostet es insgesamt?",mechanism:"Vollständiger Gegenwert und vorhersehbarer Kauf. Produktumfang und Begleitung stehen unmittelbar beim Preis.",design:"Eine weiße Angebotskarte. Produkte, Leistungen, Gesamtpreis, Hauptbutton und Lieferung sind zusammen. Orange nur für die primäre Handlung. Auf dem Handy keine konkurrierenden Kaufvarianten.",content:"Preis wird aus dem vorhandenen Katalog übernommen. In Produktion aus dem serverseitigen Angebot; Währung, Versandkosten und Einmalzahlung explizit. Keine Zahlungsdaten in URL oder Analytics.",avoid:"Kein Rabattanker, solange Vergleichspreise nicht nachgewiesen sind. Tagespreis ist kein Ersatz für Gesamtpreis. Kein verborgenes Abo.",measure:"Anteil Angebot gesehen → Checkout geöffnet → echte Bestellung → angenommene Lieferung; nicht nur Buttonklicks."},
  {id:"guarantee",title:"08 · Finanzielle Sicherheit",question:"Was ist, wenn ich nicht zufrieden bin?",mechanism:"Verständliche Bedingungen verringern finanzielle Unsicherheit. Eine Garantie belegt weder Wirksamkeit noch individuelle Verträglichkeit.",design:"Kurze Garantiezeile beim Angebot mit direkt aufklappbaren Bedingungen. Keine riesige Risiko-Parole.",content:"Vor Livegang müssen Dauer, Fristbeginn, Anspruch, Rücksendung, Ansprechpartner und Erstattungsweg zur real angebotenen Leistung passen.",avoid:"‚Ohne Risiko‘ oder ‚ohne Rückfragen‘ nur verwenden, wenn genau das tatsächlich gewährleistet ist; gesundheitliche Risiken nicht aus einer Geldgarantie ableiten.",measure:"Verstehen Personen, was die Garantie umfasst und wie sie diese nutzen?"},
  {id:"followup",title:"09 · Begleitung und Erwartungen",question:"Bin ich nach dem Kauf auf mich allein gestellt?",mechanism:"Prozesssicherheit und konkrete Erreichbarkeit statt allgemeiner Beruhigung. Die Zukunft wird als nachvollziehbarer Ablauf dargestellt.",design:"Drei Zeitpunkte: Start, Verlauf, Tag 28. Die kleine Verbindungslinie trägt hier echte zeitliche Bedeutung. Kontaktbox mit vorhandenem Porträt.",content:"Live: echte Zuständigkeit, realistischer Antwortzeitraum, Weg zur Rückmeldung, Initiator des Folgetermins und enthaltene Leistungen. Kein angeblicher täglicher Arztkontakt ohne entsprechende Leistung.",avoid:"Keine wöchentlich garantierten Hautverbesserungen und keine Normalisierung starker Reaktionen.",measure:"Wissen Kundinnen, wann und wie sie Unterstützung erhalten? Supportanfragen und Retourengründe mitbetrachten."},
  {id:"details",title:"10 · Vollständigkeit ohne Überlastung",question:"Kann ich die Beurteilung nachvollziehen?",mechanism:"Vertiefung nach Bedarf: die wesentliche Erklärung bleibt sofort sichtbar, komplexere Inhalte bleiben erreichbar. Unterschiedliche Informationsbedürfnisse werden berücksichtigt.",design:"Vier native Aufklapper: Zonen, Bedeutung, Methode/Grenzen, möglicher Verlauf. Zusammenfassungen sind mit Tastatur bedienbar. Der Methodenlink im Ergebnis öffnet den passenden Aufklapper.",content:"Im Livebericht alle anwendbaren Felder des v3-Schemas darstellen; fehlend, nicht beurteilbar und nicht zutreffend unterscheiden. Kein technischer Datenstrom in der Kundenansicht.",avoid:"Wesentliche Einschränkungen oder kaufrelevante Risiken nicht verstecken. Keine unbestimmten Zukunftsprognosen als Verkaufsargument.",measure:"Finden informationsorientierte Personen ihre Antwort, ohne andere zum Lesen sämtlicher Details zu zwingen?"},
  {id:"faq",title:"11 · Einwände beantworten",question:"Was könnte gegen den Start sprechen?",mechanism:"Relevante Zweifel werden beantwortet. Die Kundin behält Kontrolle und muss die Informationen nicht außerhalb suchen.",design:"Kurze Fragen, Antwort erst bei Bedarf. Reihenfolge: Passung, bestehende Pflege/Empfindlichkeit, Zeitraum, Reaktionen, Lieferung, Daten.",content:"Antworten aus echten Produktinformationen und Betriebsabläufen. Bei Schwangerschaft, Stillzeit, Allergien oder anderer Behandlung muss die individuelle Passung vor dem Verkauf geprüft werden.",avoid:"Keine pauschale Sicherheit für alle Hauttypen. Nicht jede Einwendung reflexartig in ein Kaufargument verwandeln.",measure:"Welche Fragen bleiben nach dem Lesen offen? Wiederkehrende Supportfragen in die Inhalte übernehmen."},
  {id:"footer",title:"12 · Verantwortlichkeit und Wiederkehr",question:"Welches Unternehmen steht dahinter, und finde ich die Seite wieder?",mechanism:"Nachprüfbarkeit als Grundlage von Vertrauen. Marke, Arztrolle und Verkäufer sind unterschiedliche Verantwortlichkeiten.",design:"Ruhiger Abschluss mit Marke, Betreiberinformationen und erreichbaren Kontakt-/Rechtslinks. Der Musterabschluss ist ehrlich als Demonstration gekennzeichnet.",content:"Vor Livebetrieb: vollständiger Betreiber, Anschrift, Kontakt, Bedingungen, Datenschutz. Anbieter kann nicht aus einem Porträt abgeleitet werden. Persönlichen Bericht nur über dafür vorgesehenen sicheren Link erneut zugänglich machen.",avoid:"Keine erfundenen Adressen, Gütesiegel oder ‚privat‘-Behauptung ohne technische Absicherung.",measure:"Kann eine neue Person den Verkäufer identifizieren und Kontakt aufnehmen?"}
];

export const LEGACY_MAP = [
  ["Briefkopf / Fallnummer", "entry", "Marke und Orientierung behalten; Fallnummer sekundär, nicht als künstliches Qualitätssiegel."],
  ["Persönliche Ansprache", "entry", "Kurze Anrede mit neutralem Fallback; offensichtliche Testnamen nicht als echte Person behandeln."],
  ["Arztporträt / Freigabedatum", "entry", "Echte Rolle und tatsächliche Prüfung unterscheiden. Musterbericht behauptet keine Freigabe."],
  ["Fotos / Parameter / Zonen", "details", "Nur verifizierte Zahlen; keine prominente Zahlenreihe vor der eigentlichen Bedeutung."],
  ["Befundabsatz", "summary", "Hauptbefund, Bedeutung und nächster Schritt in einer zusammenhängenden Fläche."],
  ["Parameterbalken", "findings", "Priorisierte Beobachtungen mit verständlicher Einordnung statt unklarer Fünferbalken."],
  ["Diagnose / Latein / Schwere / IGA", "summary", "Albanisch und international gemeinsam. IGA nur bei passend validierter Skala und echter Bewertung; hier bewusst keine pauschale IGA."],
  ["Fotogrenzen", "details", "Kurze Grundlage oben; detaillierte Grenzen direkt verlinkt. Wesentliche Unsicherheit bleibt sichtbar."],
  ["Bedeutung / Untersuchungsauftrag / Zonen", "details", "In aufklappbarer Vollanalyse erhalten, inhaltlich nicht streichen."],
  ["Verlauf ohne Pflege / Prognose", "details", "Nur fachlich begründete Aussagen; keine Angstkurve, kein vorhergesagter Schaden durch Nichtkauf."],
  ["Hautbedürfnisse / Übergangssatz", "plan", "Ein Pflegeziel und eine nachvollziehbare Verbindung zur Produktauswahl statt wiederholter Problemtexte."],
  ["Produktkarten", "products", "Rolle, Menge, tatsächliche Passung; stabile IDs statt Zuordnung nach Listenposition."],
  ["Produktbilder", "products", "Einheitliche echte Packshots später ergänzen. Vorhandene uneinheitliche Fotos und leere Symbole werden nicht als fertige Produktserie ausgegeben."],
  ["Inhaltsstoffe / Anwendung", "routine", "Kurzroutine sofort; konkrete geprüfte Formeln und Dosierung im Detail. Keine unbekannten Inhaltsstoffe erfinden."],
  ["Ziel bis Tag 28", "followup", "Kontrollzeitpunkt mit beobachtbaren Kriterien statt versprochener Hautverbesserung bis zu einem festen Datum."],
  ["Vorher / Nachher", "followup", "Optionaler Beleg, standardmäßig nicht gerendert: nur real, eingewilligt, unbearbeitet und zur Empfehlung passend. Keine künstlichen Patientenergebnisse."],
  ["Paketzusammenfassung / Preis", "offer", "Produkte und Betreuung direkt beim Gesamtpreis, Versand klar eingeschlossen."],
  ["Streichpreis / Ersparnis / Tagespreis", "offer", "Ohne belegte Vergleichspreise weglassen. Gesamtpreis hat Vorrang."],
  ["Versand / Nachnahme", "offer", "Direkt am Button, konsistent bis zum Checkout. Livepreis serverseitig bestätigen."],
  ["Vier-Wochen-Plan / Betreuung", "followup", "Drei verständliche Prozessschritte und klare Zuständigkeit, keine Heilungsetappen."],
  ["Garantie", "guarantee", "Fristbeginn und reale Bedingungen; finanzielle Erstattung nicht als medizinische Sicherheit darstellen."],
  ["FAQ / Warnhinweise", "faq", "Passung und Anwendungsfragen vor Versandfragen; relevante Risiken nicht verkleinern oder verstecken."],
  ["Bericht speichern / WhatsApp", "footer", "Nur mit sicherem Berichtslink und erklärter Übertragung. Im Muster keine Patientendaten versenden."],
  ["Anbieter / Haftung", "footer", "Verantwortliche Rollen und Verkäufer konsistent ausweisen; nicht oben Arztbericht, unten widersprüchliche Leistungsbeschreibung."],
  ["Fester Kaufbutton", "offer", "Erst nach Sichtkontakt mit dem Angebot; ausblenden, solange dessen Button sichtbar ist. Konkrete Handlung statt Druck."],
  ["Bestellformular", "offer", "Beschriftete Felder, vollständiger Preis, native Prüfung, Fokusführung, echte Bestätigung erst nach Servererfolg."],
  ["Laden / Warten / Nicht gefunden / Versandstatus", "entry", "Bestehende Livezustände bleiben unberührt. Vor Integration müssen echte Lade-, Fehler- und Bestellzustände separat verdrahtet werden; Demo lädt synchron ohne Datenbank."]
];

export const SOURCES = [
  ["Nielsen Norman Group · Trustworthiness in Web Design", "https://www.nngroup.com/articles/trustworthy-design/"],
  ["Nielsen Norman Group · Progressive Disclosure", "https://www.nngroup.com/articles/progressive-disclosure/"],
  ["Nielsen Norman Group · Interface Copy Impacts Decision Making", "https://www.nngroup.com/articles/interface-copy-decision-making/"],
  ["Baymard Institute · Payment UX", "https://baymard.com/learn/payment-ux"]
];
