export const USE_NEW_PUBLIC_MENU_RUNTIME = false;
export const USE_NEW_PUBLIC_PROFILE_RUNTIME = false;
export const USE_NEW_QR_MENU_RUNTIME = false;
export const USE_NEW_WAITER_RUNTIME = false;
export const USE_NEW_OWNER_RUNTIME = false;

export const MNYRA_FEATURE_FLAGS = Object.freeze({
  USE_NEW_PUBLIC_MENU_RUNTIME,
  USE_NEW_PUBLIC_PROFILE_RUNTIME,
  USE_NEW_QR_MENU_RUNTIME,
  USE_NEW_WAITER_RUNTIME,
  USE_NEW_OWNER_RUNTIME,
});

export default MNYRA_FEATURE_FLAGS;
